displayName=Random Timer
author=matthew OSRS
description=This plugin allows you to set a range of time in which a timer will go off at a random point
support=https://github.com/matthewxmar10/random-timer-plugin
tags=timer,fun,creative
version=
plugins=com.matthewOSRS.RandomTimerPlugin
build=standard